// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks_test.go -package=usecase_test
//

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	reflect "reflect"

	link "github.com/iamroockie/linkforge/internal/link"
	gomock "go.uber.org/mock/gomock"
)

// MockLinkSaver is a mock of LinkSaver interface.
type MockLinkSaver struct {
	ctrl     *gomock.Controller
	recorder *MockLinkSaverMockRecorder
	isgomock struct{}
}

// MockLinkSaverMockRecorder is the mock recorder for MockLinkSaver.
type MockLinkSaverMockRecorder struct {
	mock *MockLinkSaver
}

// NewMockLinkSaver creates a new mock instance.
func NewMockLinkSaver(ctrl *gomock.Controller) *MockLinkSaver {
	mock := &MockLinkSaver{ctrl: ctrl}
	mock.recorder = &MockLinkSaverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkSaver) EXPECT() *MockLinkSaverMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockLinkSaver) Save(arg0 context.Context, arg1 link.Link) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockLinkSaverMockRecorder) Save(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockLinkSaver)(nil).Save), arg0, arg1)
}
