// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks_test.go -package=rest_test
//

// Package rest_test is a generated GoMock package.
package rest_test

import (
	context "context"
	reflect "reflect"

	link "github.com/iamroockie/linkforge/internal/link"
	gomock "go.uber.org/mock/gomock"
)

// MockLinkCreator is a mock of LinkCreator interface.
type MockLinkCreator struct {
	ctrl     *gomock.Controller
	recorder *MockLinkCreatorMockRecorder
	isgomock struct{}
}

// MockLinkCreatorMockRecorder is the mock recorder for MockLinkCreator.
type MockLinkCreatorMockRecorder struct {
	mock *MockLinkCreator
}

// NewMockLinkCreator creates a new mock instance.
func NewMockLinkCreator(ctrl *gomock.Controller) *MockLinkCreator {
	mock := &MockLinkCreator{ctrl: ctrl}
	mock.recorder = &MockLinkCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkCreator) EXPECT() *MockLinkCreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLinkCreator) Create(ctx context.Context, l link.CreateLinkParams) (link.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, l)
	ret0, _ := ret[0].(link.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockLinkCreatorMockRecorder) Create(ctx, l any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLinkCreator)(nil).Create), ctx, l)
}

// MockRedirectURLProvider is a mock of RedirectURLProvider interface.
type MockRedirectURLProvider struct {
	ctrl     *gomock.Controller
	recorder *MockRedirectURLProviderMockRecorder
	isgomock struct{}
}

// MockRedirectURLProviderMockRecorder is the mock recorder for MockRedirectURLProvider.
type MockRedirectURLProviderMockRecorder struct {
	mock *MockRedirectURLProvider
}

// NewMockRedirectURLProvider creates a new mock instance.
func NewMockRedirectURLProvider(ctrl *gomock.Controller) *MockRedirectURLProvider {
	mock := &MockRedirectURLProvider{ctrl: ctrl}
	mock.recorder = &MockRedirectURLProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedirectURLProvider) EXPECT() *MockRedirectURLProviderMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockRedirectURLProvider) Get(ctx context.Context, alias string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, alias)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRedirectURLProviderMockRecorder) Get(ctx, alias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRedirectURLProvider)(nil).Get), ctx, alias)
}
