// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks_test.go -package=rest_test
//

// Package rest_test is a generated GoMock package.
package rest_test

import (
	context "context"
	reflect "reflect"

	link "github.com/iamroockie/linkforge/internal/link"
	gomock "go.uber.org/mock/gomock"
)

// MockLinkCreator is a mock of LinkCreator interface.
type MockLinkCreator struct {
	ctrl     *gomock.Controller
	recorder *MockLinkCreatorMockRecorder
	isgomock struct{}
}

// MockLinkCreatorMockRecorder is the mock recorder for MockLinkCreator.
type MockLinkCreatorMockRecorder struct {
	mock *MockLinkCreator
}

// NewMockLinkCreator creates a new mock instance.
func NewMockLinkCreator(ctrl *gomock.Controller) *MockLinkCreator {
	mock := &MockLinkCreator{ctrl: ctrl}
	mock.recorder = &MockLinkCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkCreator) EXPECT() *MockLinkCreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLinkCreator) Create(arg0 context.Context, arg1 link.CreateLinkParams) (link.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(link.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockLinkCreatorMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLinkCreator)(nil).Create), arg0, arg1)
}
